version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin # Cambia esto por tu contraseña
      MYSQL_DATABASE: sql_chatapp
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    restart: always

volumes:
  mysql-data:
