CREATE TABLE user (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE chatRoom (
    id INT AUTO_INCREMENT PRIMARY KEY,
    roomName VARCHAR(150) NOT NULL,
    messageList JSON NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- CREATE TABLE message (
--   id INT AUTO_INCREMENT PRIMARY KEY,
--   chatRoomId INT NOT NULL,
--   userName VARCHAR(150) NOT NULL,
--   message TEXT NOT NULL,
--   timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--   FOREIGN KEY (chatRoomId) REFERENCES chatRoom(id)
-- );
